from selenium.webdriver.common.by import By

user_information_title = (By.CSS_SELECTOR, ".text-2xl")
field_title = (By.ID, "title")
title_option_mr = (By.CSS_SELECTOR, "[value='Mr.']")
title_option_mrs = (By.CSS_SELECTOR, "[value='Mrs.']")
field_first_name = (By.ID, "firstName")
validation_first_name = (By.ID, "firstName-error")
field_middle_name = (By.ID, "middleName")
validation_middle_name = (By.ID, "middleName-error")
field_last_name = (By.ID, "lastName")
validation_last_name = (By.ID, "lastName-error")
field_email = (By.ID, "email")
validation_email = (By.ID, "email-error")
field_phone_number = (By.ID, "phone")
validation_phone_number = (By.ID, "phone-error")
field_dob = (By.ID, "dob")
validation_dob = (By.ID, "dob-error")
gender = (By.CSS_SELECTOR, ".slider")
field_province = (By.ID, "province")
dki_province_option = (By.XPATH, "(//option[2])[2]")
jateng_province_option = (By.XPATH, "(//option[4])[2]")
validation_province = (By.ID, "province-error")
field_city = (By.ID, "city")
validation_city = (By.ID, "city-error")
city_option_1 = (By.XPATH, "(//option[2])[3]")
submit_button = (By.CSS_SELECTOR, "[name='action']")
close_button = (By.XPATH, "//button[contains(text(),'Close')]")

# modal
name_in_modal = (By.CSS_SELECTOR, "#modalContent > p:nth-of-type(1) > strong")
gender_in_modal = (By.CSS_SELECTOR, "p:nth-of-type(2) > strong:nth-of-type(1)")
dob_in_modal = (By.CSS_SELECTOR, "p:nth-of-type(2) > strong:nth-of-type(2)")
phone_in_modal = (By.CSS_SELECTOR, "p:nth-of-type(3) > strong:nth-of-type(1)")
email_in_modal = (By.CSS_SELECTOR, "p:nth-of-type(3) > strong:nth-of-type(2)")
province_in_modal = (By.CSS_SELECTOR, "p:nth-of-type(4) > strong:nth-of-type(1)")
city_in_modal = (By.CSS_SELECTOR, "p:nth-of-type(4) > strong:nth-of-type(2)")
